FROM openeuler/openeuler:22.03

USER root

WORKDIR /root

RUN dnf install -y \
        bzip2-devel \
        ca-certificates \
        clang \
        clang-tools-extra \
        cmake \
        curl \
        gcc \
        gcc-c++ \
        git \
        lld \
        llvm \
        libffi-devel \
        liblzma-devel \
        libncurses-devel \
        libzstd-devel \
        make \
        ninja-build \
        openssl-devel \
        pkgconf-pkg-config \
        readline-devel \
        sqlite-devel \
        wget \
        xz \
        zlib-devel && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN wget https://repo.huaweicloud.com/python/3.11.15/Python-3.11.15.tar.xz && \
    tar -xvf Python-3.11.15.tar.xz && cd Python-3.11.15 && \
    mkdir -p /usr/local/python3.11.15/lib && \
    ./configure --enable-shared LDFLAGS="-Wl,-rpath /usr/local/python3.11.15/lib" --prefix=/usr/local/python3.11.15 && \
    make -j"$(nproc)" && \
    make altinstall && \
    ln -sf /usr/local/python3.11.15/bin/python3.11 /usr/local/python3.11.15/bin/python3 && \
    ln -sf /usr/local/python3.11.15/bin/pip3.11 /usr/local/python3.11.15/bin/pip3 && \
    ln -sf /usr/local/python3.11.15/bin/python3 /usr/local/python3.11.15/bin/python && \
    ln -sf /usr/local/python3.11.15/bin/pip3 /usr/local/python3.11.15/bin/pip && \
    cd /root && rm Python-3.11.15.tar.xz && rm -rf Python-3.11.15

ENV PATH=/usr/local/python3.11.15/bin:$PATH
ENV LLVM_INSTALL_PREFIX=/opt/LLVM-19.1.7

RUN wget -q https://llvm-project.obs.cn-southwest-2.myhuaweicloud.com/llvm-project-19.1.7.src.tar.xz && \
    tar -xvf llvm-project-19.1.7.src.tar.xz && \
    cd llvm-project-19.1.7.src && \
    python -m pip install --no-cache-dir -r mlir/python/requirements.txt && \
    cmake -S llvm -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL_PREFIX} \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DLLVM_ENABLE_LLD=ON \
        -DLLVM_ENABLE_PROJECTS="mlir;clang" \
        -DLLVM_TARGETS_TO_BUILD=Native \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_INSTALL_UTILS=ON \
        -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
        -DPython3_EXECUTABLE=$(which python3) \
        -DPython3_FIND_STRATEGY=LOCATION && \
    ninja -C build -j$(nproc) && \
    ninja -C build install && \
    cd /root && rm llvm-project-19.1.7.src.tar.xz && rm -rf llvm-project-19.1.7.src

CMD ["/bin/bash"]
